 // Mastering preset deck library matching real navigation lights cards
        const PRESETS = [
            // SET 1: Power & Sail
            { id: "s1-1", set: 1, title: "Power-Driven Vessel", length: "< 50m", vesselFunction: "", status: "Underway / Making way", aspect: "Head-on", daySignal: "None", soundSignal: "1 Prolonged (Fog)", rule: "Rule 23", action: "", lights: [{ x: 145, y: 90, color: "white" }, { x: 100, y: 220, color: "red" }, { x: 190, y: 220, color: "green" }] },
            { id: "s1-2", set: 1, title: "Power-Driven Vessel", length: ">= 50m", vesselFunction: "", status: "Underway / Making way", aspect: "Port Side aspect", daySignal: "None", soundSignal: "1 Prolonged (Fog)", rule: "Rule 23", action: "", lights: [{ x: 190, y: 80, color: "white" }, { x: 110, y: 130, color: "white" }, { x: 150, y: 240, color: "red" }] },
            { id: "s1-3", set: 1, title: "Sailing Vessel", length: "Any length", vesselFunction: "", status: "Underway under sail", aspect: "Starboard Side aspect", daySignal: "Cone apex down (if motor used)", soundSignal: "1 Prol. + 2 Short (Fog)", rule: "Rule 25", action: "", lights: [{ x: 145, y: 230, color: "green" }] },

            // SET 2: Fishing & Trawling
            { id: "s2-1", set: 2, title: "Engaged in Trawling", length: "< 50m", vesselFunction: "Dragging Fishing Apparatus", status: "Making way", aspect: "Port side", daySignal: "Two cones apex together", soundSignal: "1 Prol. + 2 Short", rule: "Rule 26(b)", action: "", lights: [{ x: 145, y: 90, color: "green" }, { x: 145, y: 130, color: "white" }, { x: 95, y: 230, color: "red" }] },
            { id: "s2-2", set: 2, title: "Fishing (Not Trawling)", length: "Any length", vesselFunction: "Engaged in fishing", status: "Not making way", aspect: "All-round view", daySignal: "Two cones apex together", soundSignal: "1 Prol. + 2 Short", rule: "Rule 26(c)", action: "", lights: [{ x: 145, y: 115, color: "red" }, { x: 145, y: 165, color: "white" }] },

            // SET 3: Pilot & Anchor
            { id: "s3-1", set: 3, title: "Vessel on Pilotage Duty", length: "Any length", vesselFunction: "Engaged on Pilotage Duty", status: "Underway", aspect: "Head-on", daySignal: "Flag H (Hotel)", soundSignal: "4 Short blasts (ID)", rule: "Rule 29", action: "Proceed with caution, maintain safe distance for pilot transfer.", lights: [{ x: 145, y: 80, color: "white" }, { x: 145, y: 120, color: "red" }, { x: 100, y: 220, color: "red" }, { x: 190, y: 220, color: "green" }] },
            { id: "s3-2", set: 3, title: "Vessel at Anchor", length: ">= 50m", vesselFunction: "", status: "At Anchor", aspect: "Port side", daySignal: "One Black Ball", soundSignal: "Rapid Bell 5s", rule: "Rule 30", action: "", lights: [{ x: 90, y: 140, color: "white" }, { x: 200, y: 190, color: "white" }] },

            // SET 4: NUC & RAM
            { id: "s4-1", set: 4, title: "Not Under Command (NUC)", length: "Any length", vesselFunction: "Unable to keep out of the way", status: "Making way", aspect: "Starboard Side", daySignal: "Two Black Balls", soundSignal: "1 Prol. + 2 Short", rule: "Rule 27(a)", action: "Give way. Keep clear.", lights: [{ x: 165, y: 90, color: "red" }, { x: 165, y: 130, color: "red" }, { x: 110, y: 240, color: "green" }] },
            { id: "s4-2", set: 4, title: "Not Under Command (NUC)", length: "Any length", vesselFunction: "", status: "Making way", aspect: "Head-on", daySignal: "Two Black Balls", soundSignal: "1 Prol. + 2 Short", rule: "Rule 27(a)", action: "Give way. Alter course to maintain safe passing.", lights: [{ x: 145, y: 90, color: "red" }, { x: 145, y: 130, color: "red" }, { x: 95, y: 230, color: "red" }, { x: 195, y: 230, color: "green" }] },
            { id: "s4-3", set: 4, title: "Restricted Ability to Maneuver", length: "Any length", vesselFunction: "Restricted Ability to Maneuver", status: "Not making way", aspect: "All-round", daySignal: "Ball-Diamond-Ball", soundSignal: "1 Prol. + 2 Short", rule: "Rule 27(b)", action: "Keep clear of the vessel.", lights: [{ x: 145, y: 90, color: "red" }, { x: 145, y: 130, color: "white" }, { x: 145, y: 170, color: "red" }] },

            // SET 5: Tow & CBD
            { id: "s5-1", set: 5, title: "Constrained by Draught", length: "Any length", vesselFunction: "Navigation restricted by draught", status: "Making way", aspect: "Port aspect", daySignal: "Cylinder", soundSignal: "1 Prol. + 2 Short", rule: "Rule 28", action: "Avoid crossing ahead, maintain wide berth.", lights: [{ x: 165, y: 80, color: "red" }, { x: 165, y: 120, color: "red" }, { x: 165, y: 160, color: "red" }, { x: 95, y: 240, color: "red" }] },
            { id: "s5-2", set: 5, title: "Towing (Tow > 200m)", length: "Any length", vesselFunction: "Towing astern", status: "Underway", aspect: "Starboard Side", daySignal: "Diamond", soundSignal: "1 Prol. + 2 Short", rule: "Rule 24(a)", action: "", lights: [{ x: 130, y: 80, color: "white" }, { x: 130, y: 120, color: "white" }, { x: 130, y: 160, color: "white" }, { x: 190, y: 240, color: "green" }] }
        ];

        const defaultDecks = [
            { id: 1, name: "Set 1: Power & Sail", custom: false },
            { id: 2, name: "Set 2: Fishing", custom: false },
            { id: 3, name: "Set 3: Pilot & Anchor", custom: false },
            { id: 4, name: "Set 4: NUC & RAM", custom: false },
            { id: 5, name: "Set 5: Tow & CBD", custom: false }
        ];

        const ruleTexts = {
            "Rule 23": "Rule 23 - Power-driven vessels underway:\n(a) A power-driven vessel underway shall exhibit:\n(i) a masthead light forward;\n(ii) a second masthead light abaft of and higher than the forward one;\n(iii) sidelights;\n(iv) a sternlight.",
            "Rule 24(a)": "Rule 24 - Towing and pushing:\n(a) A power-driven vessel when towing shall exhibit:\n(i) instead of the light prescribed in Rule 23(a)(i) or (a)(ii), two masthead lights in a vertical line. When the length of the tow exceeds 200 meters, three such lights in a vertical line;\n(ii) sidelights;\n(iii) a sternlight;\n(iv) a towing light in a vertical line above the sternlight;\n(v) when the length of the tow exceeds 200 meters, a diamond shape where it can best be seen.",
            "Rule 25": "Rule 25 - Sailing vessels underway and vessels under oars:\n(a) A sailing vessel underway shall exhibit:\n(i) sidelights;\n(ii) a sternlight.",
            "Rule 26(b)": "Rule 26 - Fishing vessels:\n(b) A vessel when engaged in trawling, by which is meant the dragging through the water of a dredge net or other apparatus used as a fishing appliance, shall exhibit:\n(i) two all-round lights in a vertical line, the upper being green and the lower white, or a shape consisting of two cones with their apexes together in a vertical line;\n(ii) a masthead light abaft of and higher than the all-round green light; a vessel of less than 50 meters in length shall not be obliged to exhibit such a light but may do so;\n(iii) when making way through the water, in addition to the lights prescribed in this paragraph, sidelights and a sternlight.",
            "Rule 26(c)": "Rule 26 - Fishing vessels:\n(c) A vessel engaged in fishing, other than trawling, shall exhibit:\n(i) two all-round lights in a vertical line, the upper being red and the lower white, or a shape consisting of two cones with apexes together in a vertical line;\n(ii) when there is outlying gear extending more than 150 meters horizontally from the vessel, an all-round white light or a cone apex upwards in the direction of the gear;\n(iii) when making way through the water, in addition to the lights prescribed in this paragraph, sidelights and a sternlight.",
            "Rule 27(a)": "Rule 27 - Vessels not under command or restricted in their ability to maneuver:\n(a) A vessel not under command shall exhibit:\n(i) two all-round red lights in a vertical line where they can best be seen;\n(ii) two balls or similar shapes in a vertical line where they can best be seen;\n(iii) when making way through the water, in addition to the lights prescribed in this paragraph, sidelights and a sternlight.",
            "Rule 27(b)": "Rule 27 - Vessels not under command or restricted in their ability to maneuver:\n(b) A vessel restricted in her ability to maneuver, except a vessel engaged in mineclearance operations, shall exhibit:\n(i) three all-round lights in a vertical line where they can best be seen. The highest and lowest of these lights shall be red and the middle light shall be white;\n(ii) three shapes in a vertical line where they can best be seen. The highest and lowest of these shapes shall be balls and the middle one a diamond;\n(iii) when making way through the water, a masthead light or lights, sidelights and a sternlight, in addition to the lights prescribed in subparagraph (i);\n(iv) when at anchor, in addition to the lights or shapes prescribed in subparagraphs (i) and (ii), the light, lights or shape prescribed in Rule 30.",
            "Rule 28": "Rule 28 - Vessels constrained by their draught:\nA vessel constrained by her draught may, in addition to the lights prescribed for power-driven vessels in Rule 23, exhibit where they can best be seen three all-round red lights in a vertical line, or a cylinder.",
            "Rule 29": "Rule 29 - Pilot vessels:\n(a) A vessel engaged on pilotage duty shall exhibit:\n(i) at or near the masthead, two all-round lights in a vertical line, the upper being white and the lower red;\n(ii) when underway, in addition, sidelights and a sternlight;\n(iii) when at anchor, in addition to the lights prescribed in subparagraph (i), the light, lights or shape prescribed in Rule 30 for vessels at anchor.",
            "Rule 30": "Rule 30 - Anchored vessels and vessels aground:\n(a) A vessel at anchor shall exhibit where it can best be seen:\n(i) in the fore part, an all-round white light or one ball;\n(ii) at or near the stern and at a lower level than the light forward, an all-round white light."
        };